name: 'Pull request'

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint && yarn prettier

      - name: build
        run: yarn build

      - name: Test
        run: yarn test


      
      
